### ISSUE TITLE
what protocol proto.py is following?

### ISSUE THREAD

**Issue by BK-Choi** [mathiasuk/ac-pserver#1]
Hello, I've got a question before using this.

[proto.py](https://github.com/mathiasuk/ac-pserver/blob/master/proto.py) defines codes.
However I think it is better if I know the reference(s) of the protocols to expand this project.

Could you give me links to reference page or document of the protocol?

**Comment by mathiasuk** [comment]
Hi,

I don't think there is an official protocol description, in this case I used the official example C# app which is included with Assetto Corsa (in assettocorsa\sdk\dev\acRemoteServerUDP_Example\acRemoteServerUDP_Example).
I can see that they've added three new commands in the example, so proto.py is now slightly out of date.

**Comment by BK-Choi** [comment]
@mathiasuk 
yeah, i thought this is also an official project of Kunos.
thanks for your answer and news.

one more question,
any plan to catch up with the 3 new commands? please?

**Comment by mathiasuk** [comment]
It should be pretty straightforward, I'll try to do this over the weekend!

**Comment by mathiasuk** [comment]
@BK-Choi I've updated the protocol to version 4 and added a methods for the new commands.

**Comment by BK-Choi** [comment]
@mathiasuk 
Thank you a lot!
