### ISSUE TITLE
How to Specify Plugin Ports

### ISSUE THREAD

**Issue by jackdesert** [mathiasuk/ac-pserver#2]
Hello,

I've been trying to get this codebase connected to acServer.exe for two-way communication. Probably I am not specifying ports correctly.

A question about server_cfg.ini, as referenced in the README:

'''Make sure that UDP_IP, UDP_PORT, and UDP_SEND_PORT match the values of UDP_PLUGIN_ADDRESS and UDP_PLUGIN_LOCAL_PORT of server_cfg.ini respectively.'''

It appears that the three values in the python file (UDP_IP, UDP_PORT, and UDP_SEND_PORT) match up with only two values in server_cfg.ini (UDP_PLUGIN_ADDRESS, UDP_PLUGIN_LOCAL_PORT). How exactly are these supposed to align?

So far I have tried using these values in server_cfg.ini:

    UDP_PORT=9600
    TCP_PORT=9600
    HTTP_PORT=8081
    UDP_PLUGIN_LOCAL_PORT=11000
    UDP_PLUGIN_ADDRESS=127.0.0.1:10000

And in pserver.py I have tried it both of these ways:

    # Version 1
    UDP_IP = "127.0.0.1"
    UDP_PORT = 10000
    UDP_SEND_PORT = 11000

    # Version 2
    UDP_IP = "127.0.0.1"
    UDP_PORT = 11000
    UDP_SEND_PORT = 10000

But I get no data from pserver.py.

Also when I run netstat to see what ports acServer is listening on, the only (UDP) ports listed are 9600 and (sometimes) 27036.

    $ netstat -a -v -b | grep -B 1 acServer
      TCP    0.0.0.0:8081           EC2AMAZ-FGB6RC1:0      LISTENING
     [acServer.exe]
      TCP    0.0.0.0:9600           EC2AMAZ-FGB6RC1:0      LISTENING
     [acServer.exe]
    --
      TCP    172.31.20.64:8081      46:50127               ESTABLISHED
     [acServer.exe]
      TCP    172.31.20.64:8081      83-81-49-25:57907      ESTABLISHED
     [acServer.exe]
      TCP    172.31.20.64:8081      host212-250-dynamic:61789  ESTABLISHED
     [acServer.exe]
      TCP    172.31.20.64:8081      89-95-214-168:59015    ESTABLISHED
     [acServer.exe]
      TCP    172.31.20.64:8081      159-255-236-152:52894  ESTABLISHED
     [acServer.exe]
      TCP    172.31.20.64:8081      host-176-41-54-54:63802  ESTABLISHED
     [acServer.exe]
      TCP    172.31.20.64:8081      ZG095207:60665         ESTABLISHED
     [acServer.exe]
    --
      TCP    172.31.20.64:50397     93-57-10-21:http       ESTABLISHED
     [acServer.exe]
    --
      TCP    [::]:8081              EC2AMAZ-FGB6RC1:0      LISTENING
     [acServer.exe]
      TCP    [::]:9600              EC2AMAZ-FGB6RC1:0      LISTENING
     [acServer.exe]
    --
      UDP    0.0.0.0:9600           *:*
     [acServer.exe]
    --
      UDP    [::]:9600              *:*
     [acServer.exe]

I have also used LiveTcpUdpWatch to record UDP transmissions, and it only shows UDP transmissions coming from port 9600, and they all go to other machings (none to 127.0.0.1) and none of them are sent to ports 10000 or 11000.

My firewall is disabled, and I am running pserver.py on the same machine as acServer.exe.

Is there anything else required in the server_cfg.ini to enable this UDP connectivity? For example, is some [PLUGIN_0] section required?

Does acServer.exe automatically start sending data on UDP to the appropriate location, or does it only start sending data on UDP after it receives a packet (a CSP_REALTIMEPOS_INTERVAL packet, for instance)? Or does at least one car have to be loaded into the session?

**Comment by mathiasuk** [comment]
Hi, sorry, the doc is not very clear: UDP_IP and UDP_PORT should match UDP_PLUGIN_ADDRESS, and UDP_PLUGIN_LOCAL_PORT should match UDP_SEND_PORT, so version 1 below should work.

I just tried locally, I'm running the default server_cfg.ini with only the following changes:
```
UDP_PLUGIN_LOCAL_PORT=11000        
UDP_PLUGIN_ADDRESS=127.0.0.1:10000
```
And in pserver.py I have:
```
UDP_IP = "127.0.0.1"   
UDP_PORT = 10000       
UDP_SEND_PORT = 11000  
```

I then start python3 pserver.py, and then ./acServer and pserver.py shows:
```
$ python3 pserver.py
Waiting for data from 127.0.0.1:10000
====
Protocol version: 4
====
New session started
====
Session Info
Protocol version: 4
Session index: 0/3, Current session: 0
Server name: AC_Server
Track: magione ()
Name: Practice
Type: 1
Time: 10
Laps: 0
Wait time: 0
Weather: 3_clear, Ambient temp: 18, Road temp: 24
Elapsed ms: 0
```
With netstat I can see acServer:
```
$ netstat -ulp | grep acServer

udp6       0      0 [::]:9600               [::]:*                              5303/./acServer     
udp6       0      0 [::]:11000              [::]:*                              5303/./acServer     
```

**Comment by jackdesert** [comment]
@mathiasuk Thank you for the reply. Silly me, had UDP_PLUGIN_LOCAL_PORT in server_cfg.ini twice, and presumably the second one was overwriting the first. 

Once I removed the extras, pserver.py started reading in data immediately.

I've also submitted a pull request which add more documentation to the README for newbs to UDP (like myself).
