### ISSUE TITLE
Message Types

### ISSUE THREAD

**Issue by Sam-Marsden** [mathiasuk/ac-pserver#5]
Very intresting project but i just wanted to know about the message type as i thought there was only one type as it shows in this doc? where did you get all the types i can see in your code??
https://docs.google.com/document/d/1KfkZiIluXZ6mMhLWfDX1qAGbvhGRC3ZUzjVIt5FQpp4/pub

**Comment by mathiasuk** [comment]
It's been a while and I don't quite remember, but I believe that the values were taken from the example C# UDP server which was included somewhere in the game files, unfortunately I don't have the game installed at the moment so can't check.

**Comment by mathiasuk** [comment]
Quick update, it used to be in:  assettocorsa\sdk\dev\acRemoteServerUDP_Example\acRemoteServerUDP_Example

**Comment by Sam-Marsden** [comment]
Thank you very much :)
